# Generated by Django 4.2.8 on 2023-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(max_length='10', primary_key=True, serialize=False),
        ),
    ]
